config/routes.rb
Rails.application.routes.draw do
  resources :orders
  # post 'orders/notify'

  get 'content/home'
  get 'obrigado', to: 'content#return'
  get 'panel/:code', to: 'content#panel'

  root 'content#home'
  default_url_options host: "https://prc25anos.herokuapp.com"
end

app/models/order.rb
# encoding: utf-8
class Order < ActiveRecord::Base
  validates_presence_of :name, :email

  has_many :order_notifications

  after_create :create_payment_order

  def create_payment_order
    payment = Iugu::Charge.create(token: pagseguro_code, email: email, items:
      [{ description: 'Adesão Paraná Clube 25 anos', quantity: 1, price_cents: 500*100 }],
      payer: { name: name, email: email })

    update_attribute :code, payment.invoice_id
    order_notifications.create!(code: payment.invoice_id, status: payment.message, payment_method: 'credit_card')

    NotificationMailer.order_updated(email, self).deliver
  end
end

app/models/order_notification.rb
class OrderNotification < ActiveRecord::Base
  belongs_to :order
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/content_controller.rb
class ContentController < ApplicationController
  def home
  end

  def return
  end

  def panel
    @notification = OrderNotification.find_by_code(params[:code])
    @order = @notification.order
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  skip_before_filter :verify_authenticity_token, only: :notify

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        NotificationMailer.order_created(@order.email, @order).deliver unless @order.order_notifications.last.status != 'Autorizado'

        format.html { redirect_to '/obrigado' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:name, :email, :code, :pagseguro_code, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/content_helper.rb
module ContentHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/content/home.html.erb
<h1 class="cover-heading">Compre seu ingresso para a festa do Paraná Clube de 25 anos</h1>
<p class="lead">
  Clique no botão abaixo e garanta já a sua entrada
</p>
<p class="lead">
  <a href="<%= url_for new_order_path %>" class="btn btn-lg btn-default">
    <i class="glyphicon glyphicon-shopping-cart"></i> Comprar agora
  </a>
</p>

app/views/content/panel.html.erb
<h1 class="cover-heading">Olá <%= @order.name %>!</h1>
<p class="lead">
  Seu pedido atualmente está com o status <strong><%= @notification.status %></strong>.
</p>

app/views/content/return.html.erb
<h1 class="cover-heading">Obrigado!</h1>
<p class="lead">
  Mandamos para seu email o seu convite :)
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Paraná Clube 25 anos</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js", "https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js" %>
  <![endif]-->

  <script type="text/javascript" src="https://js.iugu.com/v1"></script>

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="site-wrapper">
    <div class="site-wrapper-inner">
      <div class="cover-container">

        <div class="masthead clearfix">
          <div class="inner">
            <h3 class="masthead-brand">PRC 25 ANOS</h3>
            <ul class="nav masthead-nav">
              <li class="active"><a href="#">Home</a></li>
              <li><a href="#">Contato</a></li>
            </ul>
          </div>
        </div>

        <div class="inner cover">
          <% flash.each do |name, msg| %>
            <%= content_tag :div, :class => "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable" do %>
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
              <%= msg %>
            <% end %>
          <% end %>

          <%= yield %>
        </div>

      </div>

    </div>

  </div>
</body>
</html>

app/views/orders/_form.html.erb
<%= form_for(@order, :html => { :class => "form-horizontal" }) do |f| %>
  <% if @order.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@order.errors.count, "erros") %>:</h4>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, "Nome", :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, :class => "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :email, "Email", :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :email, :class => "form-control" %>
    </div>
  </div>

  <%= f.hidden_field :pagseguro_code %>

  <fieldset>
    <legend>Dados de Pagamento</legend>
      <div class="form-group">
        <label class="col-sm-3 control-label">Nome</label>
        <div class="col-sm-9">
          <input type="text" data-iugu="first_name" class="form-control">
        </div>
      </div>
      <div class="form-group">
        <label class="col-sm-3 control-label">Sobrenome</label>
        <div class="col-sm-9">
          <input type="text" data-iugu="last_name" class="form-control">
        </div>
      </div>
      <div class="form-group">
        <label class="col-sm-3 control-label">Numéro do Cartão</label>
        <div class="col-sm-9">
          <input type="text" data-iugu="number" class="form-control">
        </div>
      </div>
      <div class="form-group">
        <label class="col-sm-3 control-label">Validade</label>
        <div class="col-sm-9">
          <div class="row">
            <div class="col-xs-6">
              <input type="text" data-iugu="expiration" class="form-control" placeholder="MM/AA">
            </div>
          </div>
        </div>
      </div>
      <div class="form-group">
        <label class="col-sm-3 control-label">CVV</label>
        <div class="col-sm-3">
          <input type="text" data-iugu="verification_value" class="form-control">
        </div>
      </div>
    </fieldset>

  <div class="form-group">
    <div class="col-sm-offset-1 col-sm-10">
      <%= f.submit "Pagar agora", :class => "btn btn-success" %>
    </div>
  </div>
<% end %>

app/views/orders/edit.html.erb
<div class="page-header">
  <%= link_to orders_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @order, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing order</h1>
</div>

<%= render 'form' %>

app/views/orders/index.html.erb
<div class="page-header">
  <%= link_to new_order_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Order
  <% end %>
  <h1>Listing orders</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Code</th>
            <th>Pagseguro code</th>
            <th>Status</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @orders) do |order| %>
            <td><%= order.name %></td>
            <td><%= order.email %></td>
            <td><%= order.code %></td>
            <td><%= order.pagseguro_code %></td>
            <td><%= order.status %></td>
            <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/orders/new.html.erb
<div class="page-header">
  <h1>Informe seus dados</h1>
</div>

<p>Enviaremos por email as próximas instruções.</p>
<p>Preencha os detalhes abaixo e prossiga para o pagamento para continuarmos o processo.</p>

<br>

<%= render 'form' %>

app/views/orders/show.html.erb
<div class="page-header">
  <%= link_to orders_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_order_path(@order), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show order</h1>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @order.name %></dd>

  <dt>Email:</dt>
  <dd><%= @order.email %></dd>

  <dt>Code:</dt>
  <dd><%= @order.code %></dd>

  <dt>Pagseguro code:</dt>
  <dd><%= @order.pagseguro_code %></dd>

  <dt>Status:</dt>
  <dd><%= @order.status %></dd>

</dl>